name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Set file extension
        id: set_extension
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            echo "extension=.exe" >> $GITHUB_OUTPUT
          else
            echo "extension=" >> $GITHUB_OUTPUT
          fi

      - name: Archive binary
        run: |
          cd target/${{ matrix.target }}/release
          zip ping_server-${{ matrix.target }}.zip ping_server${{ steps.set_extension.outputs.extension }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ping_server-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ping_server-${{ matrix.target }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
