name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Grants write permission to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Set file extension and artifact name
        id: set_names
        run: |
          # Determine the file extension based on the target
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            echo "extension=.exe" >> $GITHUB_OUTPUT
          else
            echo "extension=" >> $GITHUB_OUTPUT
          fi

          # Simplify the target triple for artifact naming
          simplified_target=${{ matrix.target }}
          simplified_target=${simplified_target/unknown-/}
          simplified_target=${simplified_target/pc-/}

          echo "simplified_target=$simplified_target" >> $GITHUB_OUTPUT

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: pingResponder-${{ steps.set_names.outputs.simplified_target }}
          path: target/${{ matrix.target }}/release/pingResponder${{ steps.set_names.outputs.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
